Sprint 2
lukyanov-anton/middle.messenger.praktikum.yandex pull request #4
Opened 2022-04-07 15:19 UTC by lukyanov-anton

2022-04-08 05:15 UTC, agadoev commented on package.json
> +    "eslint": "eslint",
Сейчас если написать npm run eslint, то линтер не запустится. Ему нужно указать путь к файлам, которые надо проверять. Например eslint ./src

2022-04-08 05:23 UTC, agadoev commented on src/components/ImagePlaceholder/imagePlaceholder.css
> +  width: 34;
Тут лучше указать единицы измерения

2022-04-08 05:56 UTC, agadoev commented on src/helpers/renderDOM.ts
> +  const root = document.querySelector(selector);
querySelector может вернуть null
Если при вызове функции renderDOM указать селектор несуществующего блока или печататься, то вылетит Exception "Cannot read properties of null (reading 'innerHTML') ". Действительно, код не должен работать в этом случае, но нужно это исключение обработать и дать понять в чем дело, например выдать ошибку "неправильно указан селектор" или что-то подобное

2022-04-08 06:01 UTC, agadoev commented on src/modules/validation/login.ts
> +    if(length<3 || length >20)
числа 3 и 20 нужно поместить в именованные константы, т.к. с первого взгляда не сразу понятно о чем они. Такие числа еще называются магическими константами и лучше их избегать

2022-04-08 06:05 UTC, agadoev commented on src/modules/validation/login.ts
> +        return ValidationResult.fail("Логин может содержать цифры, но не состоять из них, латиница, без пробелов, без спецсимволов (допустимы дефис и нижнее подчёркивание).");
строковый литерал сообщения об ошибке лучше не держать  в коде и постараться максимально отделить его от кода. У тебя для этого есть хорошее решение, в файле stubs.ts. Я бы перенес все сообщения валидации в этот файл

Тогда как использовать их в этой функции? 
1) Можно либо просто заимпортить
2) Пробрасывать через аргументы функции. Этот вариант предпочтительнее, т.к. делает твою функцию чище, универсальнее и более переиспользуемой

2022-04-08 06:13 UTC, agadoev commented on src/stubPages/chats.ts
> +import LinkBlock from "../components/link";
Вот тут нужно пофиксить импорты, т.к. в они указывают на несуществующие папки
Я подозреваю, что из-за этого падает тест на роутинг 

<img width="678" alt="Screenshot 2022-04-08 at 09 12 50" src="https://user-images.githubusercontent.com/37894659/162375394-f5403a7a-1f69-426c-a813-216180b5ebc9.png">

2022-04-08 06:16 UTC, agadoev commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig.json to read more about this file */
Неплохая идея оставить все свойства закомментированными, еще и с описанием, чтобы в будущем если что "включить" их. Однако сейчас файл выглядит загроможденным и нечитаемым. Если нужно будет почитать описание какого-либо свойства - всегда есть документация на официальном сайте

Также нужно включить вот эти свойства для более строгой статической проверки
"noImplicitAny": true,
"noUnusedLocals": true,
"noUnusedParameters": true,

2022-04-08 06:25 UTC, agadoev requested changes
Привет! 

Из обязательных моментов:
1) Не проходит тесты на роутинг (я отписал в комментах возможную причину)
2) Неправильно настроен tsconfig

В целом работая хорошая, я обратил внимание на несколько деталей, которые нужно исправить

2022-04-08 07:11 UTC, lukyanov-anton commented on src/stubPages/chats.ts
> +import LinkBlock from "../components/link";
У меня такой ошибки нет. Было переименование папок. Была первая заглавная буква, сейчас строчная.

2022-04-08 07:18 UTC, lukyanov-anton commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig.json to read more about this file */
Убрал все комментарии, включил три параметра проверки

2022-04-09 03:27 UTC, lukyanov-anton commented
Проверку роутинга закомментировал с разрешения наставника, так как не удалось запустить ее на сервере, локально тест проходит

2022-04-10 10:28 UTC, agadoev approved these changes
Привет! Работу принимаю, пофиксь только конфликты и можно мержить

2022-04-16 08:37 UTC, merged